name: "PDLC Stage 4: Build"
description: "Implement the plugin. One Issue = one PR, TDD as the default."
title: "[build] "
labels: ["stage/build"]
body:
  - type: markdown
    attributes:
      value: |
        **PDLC Stage 4 — Build.** Implement the skills, hooks, agents, MCP servers, LSP servers, and commands.

        Build follows a disciplined cycle: one Issue = one PR, TDD as the implementation approach.

        > **Reminder:** Assign this issue to the plugin's milestone and add the `plugin/<name>` label.

  - type: input
    id: plugin-name
    attributes:
      label: Plugin name
      description: "Kebab-case. Must match the milestone name."
      placeholder: "documentation-authoring"
    validations:
      required: true

  - type: input
    id: design-issue
    attributes:
      label: Design issue
      description: "Link to the completed Design stage issue (e.g., #45)."
      placeholder: "#45"
    validations:
      required: true

  - type: checkboxes
    id: entry-criteria
    attributes:
      label: Entry criteria
      description: Confirm before starting this stage.
      options:
        - label: Design stage is complete and issue is closed
          required: true
        - label: Code Actual has approved the design
          required: true
        - label: Primitives identified and boundaries drawn
          required: true

  - type: textarea
    id: implementation-plan
    attributes:
      label: Implementation plan
      description: "Break the build into sub-issues. Each sub-issue = one PR. Track them here as a checklist."
      placeholder: |
        - [ ] #51 — Implement core skill (SKILL.md + references)
        - [ ] #52 — Implement agent definition
        - [ ] #53 — Implement hooks
        - [ ] #54 — Implement commands
      value: |
        <!-- Update this list as sub-issues are created -->
    validations:
      required: true

  - type: textarea
    id: composition-testing
    attributes:
      label: Composition testing plan
      description: "For core plugins: how will you verify composition with existing core plugins? For standalone: note N/A."
      placeholder: |
        - Install alongside plugin-authoring, verify no hook conflicts
        - Test that agent roles don't overlap without adding value
    validations:
      required: false

  - type: checkboxes
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: All must be checked before closing this issue and moving to Prove.
      options:
        - label: All primitives implemented
        - label: Tests passing
        - label: No known composition conflicts with existing core plugins
        - label: Plugin can be installed and used from a clean state
        - label: All sub-issue PRs merged
