name: "PDLC Stage 2: Research"
description: "Study the domain. This is where 'we study before we sell' lives."
title: "[research] "
labels: ["stage/research"]
body:
  - type: markdown
    attributes:
      value: |
        **PDLC Stage 2 — Research.** Study the domain deeply enough to form an opinionated view of how it should work.

        Start with academic papers and published industry research. Then community practice, handled with care. This stage can take time. That's fine.

        > **Reminder:** Assign this issue to the plugin's milestone and add the `plugin/<name>` label.

  - type: input
    id: plugin-name
    attributes:
      label: Plugin name
      description: "Kebab-case. Must match the milestone name."
      placeholder: "documentation-authoring"
    validations:
      required: true

  - type: input
    id: concept-issue
    attributes:
      label: Concept issue
      description: "Link to the completed Concept stage issue (e.g., #43)."
      placeholder: "#43"
    validations:
      required: true

  - type: checkboxes
    id: entry-criteria
    attributes:
      label: Entry criteria
      description: Confirm before starting this stage.
      options:
        - label: Concept stage is complete and issue is closed
          required: true
        - label: Code Actual has approved the concept
          required: true

  - type: textarea
    id: research-questions
    attributes:
      label: Research questions
      description: "What specific questions does this research need to answer? These guide the study."
      placeholder: |
        1. What does the academic literature say about...?
        2. What are the established best practices for...?
        3. Where is the community consensus, and where is it divided?
    validations:
      required: true

  - type: textarea
    id: known-sources
    attributes:
      label: Known sources
      description: "Starting points for the research. Papers, tools, prior art, community resources."
      placeholder: |
        - Paper: "Title" (Author, Year)
        - Tool: https://...
        - Community resource: ...
    validations:
      required: false

  - type: textarea
    id: scope-notes
    attributes:
      label: Scope notes
      description: "Any boundaries on the research? Domains to include or deliberately exclude?"
    validations:
      required: false

  - type: checkboxes
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: All must be checked before closing this issue and moving to Design.
      options:
        - label: Sufficient domain understanding to form an opinionated view
        - label: Key sources are documented in this issue
        - label: Open questions are identified
        - label: Research documents created in `docs/research/` (if applicable)
