#!/usr/bin/env python3
"""Index Architecture Decision Records by parsing YAML front matter.

Generates docs/decisions/_INDEX.md from all ADR files in the same directory.
Run from the project root: python scripts/index_decisions.py
"""

from pathlib import Path
import re
import sys

DECISIONS_DIR = Path("docs/decisions")
INDEX_FILE = DECISIONS_DIR / "_INDEX.md"
FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
ADR_NUMBER_RE = re.compile(r"^(\d{4})-")


def parse_front_matter(path: Path) -> dict | None:
    """Extract front matter fields without a YAML dependency.

    Handles both inline lists [a, b] and block lists (- item).
    """
    text = path.read_text(encoding="utf-8")
    match = FRONT_MATTER_RE.match(text)
    if not match:
        return None

    fields = {}
    current_key = None
    current_list = None

    for line in match.group(1).splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        # Block list item: "  - value"
        if line.startswith("  - ") and current_key is not None:
            if current_list is None:
                current_list = []
            current_list.append(line.strip()[2:].strip())
            fields[current_key] = current_list
            continue

        # Flush any pending list
        current_list = None

        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        current_key = key

        # Inline list: [a, b, c]
        if value.startswith("[") and value.endswith("]"):
            value = [v.strip().strip("\"'") for v in value[1:-1].split(",") if v.strip()]
        # Quoted string
        elif value.startswith(("'", '"')) and value.endswith(("'", '"')):
            value = value[1:-1]
        # Null
        elif value == "null":
            value = None
        # Empty value (block list follows on next lines)
        elif value == "":
            current_list = []
            value = current_list

        fields[key] = value

    return fields


def collect_adrs(directory: Path) -> list[dict]:
    """Collect and parse all ADR markdown files."""
    entries = []
    for path in sorted(directory.glob("*.md")):
        if path.name in ("_INDEX.md", "_TEMPLATE.md"):
            continue
        if not ADR_NUMBER_RE.match(path.name):
            continue
        meta = parse_front_matter(path)
        if meta is None:
            print(f"  warning: no front matter in {path.name}, skipping")
            continue
        meta["filename"] = path.name
        # Extract ADR number from filename
        num_match = ADR_NUMBER_RE.match(path.name)
        meta["number"] = num_match.group(1) if num_match else "????"
        entries.append(meta)
    return entries


def status_icon(status: str) -> str:
    return {
        "draft": "\u270f\ufe0f",
        "proposed": "\U0001f4ac",
        "accepted": "\u2705",
        "superseded": "\U0001f504",
        "deprecated": "\u274c",
    }.get(status, "\u2753")


def build_index(entries: list[dict]) -> str:
    lines = [
        "# Decision Records Index",
        "",
        "<!-- Auto-generated by scripts/index_decisions.py. Do not edit. -->",
        "",
    ]

    # Summary counts
    by_status = {}
    for e in entries:
        s = e.get("status", "unknown")
        by_status[s] = by_status.get(s, 0) + 1

    status_summary = " \u00b7 ".join(
        f"{status_icon(s)} {s}: {c}" for s, c in sorted(by_status.items())
    )
    lines.append(f"{len(entries)} decisions \u2014 {status_summary}")
    lines.append("")

    # Main table
    lines.append("| # | Status | Date | Decision | Decision-makers |")
    lines.append("|---|--------|------|----------|-----------------|")

    for e in entries:
        number = e.get("number", "????")
        status = e.get("status", "unknown")
        icon = status_icon(status)
        date = e.get("date", "?")
        title = e.get("title", e["filename"])
        makers = e.get("decision-makers", [])
        makers_str = ", ".join(makers) if isinstance(makers, list) else str(makers)
        link = f"[{title}](./{e['filename']})"
        lines.append(f"| {number} | {icon} {status} | {date} | {link} | {makers_str} |")

    lines.append("")
    return "\n".join(lines)


def main():
    if not DECISIONS_DIR.is_dir():
        print(f"error: {DECISIONS_DIR} does not exist")
        sys.exit(1)

    entries = collect_adrs(DECISIONS_DIR)
    print(f"found {len(entries)} ADR(s)")

    index_content = build_index(entries)
    INDEX_FILE.write_text(index_content, encoding="utf-8")
    print(f"wrote {INDEX_FILE}")


if __name__ == "__main__":
    main()
